apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-2048
  namespace: dev
  annotations:
    # Annotations to be detected by Keel for image update configuration.
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/container: react-app-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
      annotations:
        keel.sh/last-updated: "{{ now }}" # <-- This line forces a rollout
    spec:
      containers:
      - name: react-app-container
        image: 475882391631.dkr.ecr.us-east-2.amazonaws.com/react-app-2048-ss-githmin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
