# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-2048
  namespace: dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: 475882391631.dkr.ecr.us-east-2.amazonaws.com/react-app-2048-ss-githmin
    argocd-image-updater.argoproj.io/image-tag-update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd # or 'git' if you're using GitOps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: 475882391631.dkr.ecr.us-east-2.amazonaws.com/react-app-2048-ss-githmin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
