apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.12.1"
    chart: argocd-image-updater
    helm:
      values: |
        config:
          registries:
            - name: ECR
              api_url: https://475882391631.dkr.ecr.us-east-2.amazonaws.com
              prefix: 475882391631.dkr.ecr.us-east-2.amazonaws.com
              ping: yes
              default: true
          logLevel: debug
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
