apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 475882391631.dkr.ecr.us-east-2.amazonaws.com/react-app-2048-ss-githmin
    argocd-image-updater.argoproj.io/write-back-method: argocd # or use 'git' if you are using GitOps write-back
    argocd-image-updater.argoproj.io/image-tag-update-strategy: latest
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.12.1"
    chart: argocd-image-updater
    helm:
      values: |
        config:
          registries:
            - name: ECR
              api_url: https://475882391631.dkr.ecr.us-east-2.amazonaws.com
              prefix: 475882391631.dkr.ecr.us-east-2.amazonaws.com
              ping: yes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
